name: Continuous Integration

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run lint and test
        uses: actions/setup-node@v3
        with:
          node-version: 22.3.0
      - run: yarn install --immutable
      - run: yarn run test